### ISSUE TITLE
Winning conditions do not translate well to larger boards

### ISSUE THREAD

**Issue by radomirbosak** [noyralf/piskvorky#1]
For example, for 4x4 board, only the upper-left 3x3 sub-board is checked for winning conditions (plus the first 3 columns for horizontal win, and first 3 rows for vertical win).

Expected: 3 X-es anywhere would win the game
e.g.
```
  0 1 2 3
0 _ _ _ _
1 _ _ _ _
2 _ X X X
3 _ _ _ _
```

Reality: The game continues

**Comment by noyralf** [comment]
The game now only works with 3x3 board. However, it was designed for possible easy extension in future. I need to change function for evaluating victory, which is hardcoded for 3x3 board.

Problem is that I am not sure about the rules for other than 3x3 board. How many tiles for vertical/horizontal/diagonal win you need to have for other boards? That's the reason why it works only for 3x3 board.

**Comment by radomirbosak** [comment]
lndeed, the rules are unclear at this point :)

Maybe for starters, we can make to rule to be "3 tiles to win" for every board size.

Then an enhancement to the game could be to generalize this to "`x` tiles to win" where `x` would be the second game parameter (the first being board size).

**Comment by noyralf** [comment]
I rewrote the function and made it more general. Now it checks N tiles to win for NxN board, which is basically a (n,n,n) game. I plan more generalization like you suggested in future.

**Comment by radomirbosak** [comment]
Thank you. The victory conditions now work correctly for nxn board with n-tile win. Closing this issue.
